### ISSUE TITLE
embedded hibari

### ISSUE THREAD

**Issue by dado112233** [hibari/hibari#40] opened 2015-02-16 11:35 UTC
Hi Tatsuya,

I m not sure this is the right place to ask but i couldn't find anything in the documentation on the subject of embedded hibari.

I m trying to build a real-time, self learning data management platform and i would like to use hibari as the default data storage system but i could not find anything that explains how to embed hibari into my application.

Is that even possible with hibari? the idea is to add hibari as rebar dependency and add it to the main application supervisor tree.

thanks,
Dalibor

**Comment by tatsuya6502** [comment] 2015-02-17 09:29
Hi Dalibor, 

Thanks for your interest in Hibari. We have never used Hibari in embedded manner, but you're right, this should be possible. If you give me a couple of days, I will try such a configuration and write brief instructions with a sample rebar.conf.

One question. What Erlang/OTP release are you using for your application? I believe the latest stable Hibari release v0.1.10 won't compile under OTP 17. I know where to update ([details](https://github.com/hibari/hibari/issues/37)), so if you are using OTP 17, I will cut a new release v0.1.11 that will be compatible with 17.

Thanks,

**Comment by dado112233** [comment] 2015-02-17 09:46
Hi Tatsuya,

thanks for you quick replay :) :) :) :)


i am planing on using the latest stable OTP but also the older versions are
possible, it depends whether you have time/energy to make the update for
OTP 17.

regards,
Dalibor

**Comment by dado112233** [comment] 2015-02-25 09:28
Hi Tatsuya,

Did you had any chance to look into this?

I tried changing the hibari to compile on 17.4 but i had some issues after changing the names reported by the compiler.

regards,
Dalibor

**Comment by tatsuya6502** [comment] 2015-02-26 07:24
Hi Dalibor,

Sorry for not getting back to you sooner. I'm on a business trip until next Thursday (Mar 5th), and haven't found enough time working on it. In last week, I only created a rebar.config on my local PC and confirmed it (v0.1.10) can build under OTP R15B03-1.

As for compiling Hibari v0.1.10 on OTP 17.4, let me try to fix it quickly as I've already done this before for dev branch of Hibari.

Thanks,

**Comment by tatsuya6502** [comment] 2015-02-26 12:31
> As for compiling Hibari v0.1.10 on OTP 17.4, let me try to fix it quickly as I've already done this before for dev branch of Hibari.

I created [#41 Update Hibari master branch (v0.1.x) for Erlang/OTP 17.x](https://github.com/hibari/hibari/issues/41) to track this task.

**Comment by dado112233** [comment] 2015-02-26 14:05
thanks :) :) :) :)

**Comment by tatsuya6502** [comment] 2015-02-27 04:39
Hi Dalibor, 

I have created Hibari `release-0.1.11` branch and updated Hibari to be compatible with Erlang/OTP 17.4. Can you please try if you can compile it on OTP 17.4 and run it in stand-alone mode (not embedded mode)? You have to checkout the branch so please follow the steps below.

**Get Hibari release-0.1.11 (pre-release)**

```
$ mkdir ~/hibari-0.1.11
$ cd hibari-0.1.11
$ repo init -u git://github.com/hibari/manifests.git -m hibari-default.xml -b release-0.1.11
$ repo sync
$ repo forall -c "git branch release-0.1.11 origin/release-0.1.11"
$ repo forall -c "git checkout release-0.1.11"
$ repo status
project hibari/                                 branch release-0.1.11
project hibari-doc/                             branch release-0.1.11
project hibari/lib/asciiedoc/                   branch release-0.1.11
project hibari/lib/cluster_info/                branch release-0.1.11
project hibari/lib/congestion_watcher/          branch release-0.1.11
project hibari/lib/edown/                       branch release-0.1.11
project hibari/lib/gdss_admin/                  branch release-0.1.11
project hibari/lib/gdss_brick/                  branch release-0.1.11
project hibari/lib/gdss_client/                 branch release-0.1.11
project hibari/lib/gmt_util/                    branch release-0.1.11
project hibari/lib/meck/                        branch release-0.1.11
project hibari/lib/partition_detector/          branch release-0.1.11
project hibari/lib/riak_err/                    branch release-0.1.11
```

**Compile and Run Hibari**

```
$ cd ~/hibari-0.1.11/hibari/
$ make compile

# To create a release tarball, install Hibari into ./tmp (under current dir) and run it.
$ make bootstrap-package
$ ./tmp/hibari/bin/hibari ping
pong
$ ./tmp/hibari/bin/hibari stop
ok

# To run a smoke test
$ make check-package

# To create a release tarball
$ make package
```

Note that I removed UBF stuff as UBF version 1 is not compatible with OTP 17. Therefore only native Erlang client API will be available in Hibari v0.1.11. 

If you have any questions, you can continue to post them to this GitHub issue, or if you prefer, you can send direct emails to me at `tatsuya at hibaridb.org` (replace `at` with `@`). Maybe [this mailing list post](https://groups.google.com/d/msg/hibaridb-users/aEyY4p1vuxc/I56vbi_TZq0J) will help you to figure out how to set up your Erlang client application (Well, maybe not). But don't hesitate to ask me some questions.

Thanks!

**Comment by tatsuya6502** [comment] 2015-03-07 18:19
For the record -- 

With @dado112233's help, we were able to build `Hibari release-0.1.11` on Ubuntu on Feb 27, 2015. To do that, he had to remove broken symbolic links created by `repo` command.

I created the following GitHub issue to address it:
[#47 reltool command will fail to generate package due to broken links created by repo command](https://github.com/hibari/hibari/issues/47)

**Comment by tatsuya6502** [comment] 2015-03-07 18:25
Now I'm working on an Erlang application skeleton for embedded Hibari. I'll check it in under [hibari](https://github.com/hibari) or [hibari-labs](https://github.com/hibari-labs) organisation soon.

**Comment by tatsuya6502** [comment] 2015-03-10 16:49
Hi @dado112233 -

I checked in my initial stuff to hibari-labs organisation. At this point, you can bootstrap single-node embedded Hibari server. Please see README for details.

- [hibari-labs/embedded-hibari-sample](https://github.com/hibari-labs/embedded-hibari-sample)

**Comment by tatsuya6502** [comment] 2015-03-10 16:55
I'm closing this issue. Please feel free to ask some questions by direct email or at [the issue page](https://github.com/hibari-labs/embedded-hibari-sample/issues) of the project.

I'll continue working on the project in my spare time.

Thanks,

**Closed by tatsuya6502** 2015-03-10 16:55 UTC
Labels: New Feature

**Comment by dado112233** [comment] 2015-03-11 11:34
thanks!!!

I will give it a try...hopefully this weekend.

regards,
Dalibor
